services:
  db:
    image: postgres:16
    container_name: dl-wallet-db
    environment:
      - POSTGRES_DB=dlwallet_db
      - POSTGRES_USER=app_admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: dl-wallet-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/dlwallet_db
      - DB_USER=app_admin
      - DB_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update